% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  12pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[a4paper]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead{}
\fancyhead[R]{\small 2025-04-10}
\fancyhead[L]{\small Regression Linéaire}
\renewcommand{\headrulewidth}{0.4pt}
\usepackage[labelfont=bf, labelsep=colon, position=top]{caption} % Place la légende au-dessus de la figure
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdfauthor={Dimitri DELPECH,; Timothé FADENIPO,; Matthis ARVOIS,; Ismael MADOU GAGI GREMA,; Cheikh LO},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{\fbox{\huge Regression Linéaire}}
\author{Dimitri DELPECH, \and Timothé FADENIPO, \and Matthis
ARVOIS, \and Ismael MADOU GAGI GREMA, \and Cheikh LO}
\date{2025-04-10}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\newpage

\section{Introduction}\label{introduction}

Le béton est un matériau très utilisé dans la construction, car il est
solide, résistant dans le temps et peut être façonné facilement. Parmi
ses propriétés, la résistance à la compression est la plus importante.
Elle correspond à la capacité du béton à supporter une charge sans se
casser. C'est cette résistance qui garantit la stabilité et la
durabilité des ouvrages.

Cette résistance dépend de plusieurs facteurs : la quantité de ciment,
d'eau, de granulats, d'adjuvants (ou additifs), mais aussi de l'âge du
béton. Chaque composant joue un rôle, et c'est souvent leur combinaison
qui influence le résultat final. Comprendre ces effets est essentiel
pour concevoir un béton performant.

Dans ce travail, on cherche à identifier les facteurs qui ont un impact
sur la résistance du béton à la compression, à partir de données
mesurées en laboratoire.

On commence d'abord par une revue empirique qui présente ce que disent
les études sur les effets des différents composants du béton. Ensuite,
on passe à l'analyse des résultats obtenus avec notre modèle linéaire.

\section{Developpemnt}\label{developpemnt}

\subsection{Revue empirique}\label{revue-empirique}

La résistance du béton est une propriété reconnue depuis longtemps. Si
le béton est un élément important du développement de nos sociétés,
c'est qu'il possède une résistance mécanique, en particulier à la
compression, qui a permis aux architectes et concepteurs de concevoir
des structures de plus en plus importantes et durables dans le temps. La
propriété de la résistance du béton reste la propriété la plus
importante du matériau pour du point de vue de l'ingénieur. Depuis
longtemps, la relation entre la composition du béton et la résistance au
béton fait écho dans le monde du génie civil et intéresse de nombreux
chercheurs de ce domaine. Cependant aucune théorie fondamentale et
universellement adoptée n'existe, en la matière, au-delà de la notion
commune de rapport eau/ciment. Cette première partie a pour but de
mettre en lumière les effets des variables explicatives sur la variable
cible en l'occurrence sur la résistance à la compression du béton en se
basant sur les travaux effectués dans ce sens.

Bien que dans toute approche fondamentale de la résistance à la
compression, la nature du granulat représente un rôle secondaire
néanmoins ceci reste important pour notre étude. Dans les années 1960,
Walker et Bloem ont publié dans leur article (Effect of Aggregate size
on properties of concrete, journal of AIC,septembre) un résultat assez
percutant. Il s'agit de la démonstration de l'effet négatif du volume de
la dimension maximale sur la résistance. Trois effets du granulat sur la
résistance du béton ont été énumérés à savoir un effet d'adhérence ;
l'effet de confinement et l'effet plafond (le Bulletin des Laboratoires
des Ponts et Chaussées, numéro 219, en janvier-février 1999, pages 41 à
52.).

A part son rôle important dans le phénomène de l'hydratation, l'eau est
l'un des facteurs les plus importants au niveau de l'ouvrabilité du
béton. L'augmentation du dosage en eau augmente la fluidité du béton et
entraîne la diminution de la concentration en solides. Cependant,
l'introduction excessive de l'eau provoque la chute de la résistance
mécanique et sa durabilité (effect on composition parameters on fresh
state properties of self-compacting concrete N.Bouhamou et al.). Le
bulletin publié par FEBELCEM (Fédération de l'Industrie Cimentière
Belge) avec l'auteur Ir C.Ployaert que la durabilité d'un béton dépend
d'une faible porosité. De plus, pour les surfaces de bétonnage non
coffrées sont les plus critiques du fait de leur exposition au soleil et
au vent. Le contrôle de leur protection efficace contre toute
évaporation intempestive de l'eau nécessaire à l'hydratation du ciment
revêt d'une grande importance. D'où la liaison importante entre la
résistance à la compression et l'eau.

Puis dans l'article publié par le département de génie civil à
l'université de Mostaganem en Algérie, le rôle de superplastifiant a été
mis en exergue. Le volume d'eau augmente avec l'augmentation du dosage
en superplastifiant. L'une des explications avancées est l'augmentation
de la viscosité de l'eau due au superplastifiant. De plus, il est noté
que l'augmentation du dosage en superplastifiant a engendré une
augmentation du taux de ségrégation statique dans le cas où le dosage
est élevé entraînant ainsi une réduction de l'homogénéité du béton et
par conséquent une réduction sa résistance à la compression. Par
ailleurs, un dosage modéré en superplastifiants apporte un bénéfice
supplémentaire, particulièrement aux premiers âges (48h, 72h), en raison
d'une meilleure compacité et d'une dispersion plus efficace des grains
de ciment.

Ensuite, Mehta et Monteiro (2014) soulignent que l'augmentation de la
teneur en ciment améliore significativement la résistance mécanique, en
particulier dans les premiers jours de durcissement. De même, Siddique
et al.~(2011) ont observé une corrélation positive entre la teneur en
ciment et la résistance à la compression, confirmant que cette relation
est particulièrement marquée dans les premières phases de durcissement.
Toutefois, au-delà d'un certain seuil, une concentration excessive de
ciment peut entraîner des effets négatifs, notamment une élévation de la
chaleur d'hydratation et une augmentation du retrait, favorisant ainsi
l'apparition de fissures (Neville, 2011). Il a également spécifié qu'il
existe une diminution dans l'efficacité du ciment en appliquant de très
haut dosage même en présence de superplastifiant dans ADDIS B.J ,
Alexandre M.G (1994) . Le dosage du ciment dans le béton est très
souvent relié à ses propriétés mécaniques et sa durabilité (effect on
composition parameters on fresh state properties of self-compacting
concrete N.Bouhamou et al.).

Par ailleurs, le laitier de haut fourneau est souvent utilisé pour
remplacer une partie du ciment afin d'améliorer certaines propriétés du
béton. Plusieurs études ont montré que son ajout réduit la résistance du
béton dans les premiers jours, car sa réaction est plus lente que celle
du ciment classique. Cependant, à plus long terme, il aide à renforcer
le béton grâce à une réaction chimique qui produit des éléments solides
supplémentaires, améliorant ainsi sa résistance (Jin et al., 2003).

De plus, l'utilisation des cendres volantes pour remplacer une partie du
ciment a aussi un impact sur la résistance du béton. D'après Tan et
al.~(2016), leur ajout réduit la résistance dans les premiers jours, car
elles réagissent plus lentement que le ciment. Toutefois, avec le temps,
elles renforcent la structure du béton et améliorent sa durabilité grâce
à une réaction chimique progressive. Zhao et al.~(2019) précisent que
leur effet dépend de la quantité utilisée et de la finesse des
particules, ce qui influence directement la résistance finale du béton.

En outre, Les granulats fins, communément appelés ``Fine Aggregate'',
constituent la fraction sableuse dans la formulation du béton. On
considère généralement qu'il s'agit de particules de dimensions
inférieures à 5 mm. La quantité de granulats fins, principalement
constitués de sable, influence la résistance du béton. Selon Chatterji
(2013), une bonne proportion de granulats fins améliore la compacité du
mélange, réduit la porosité et augmente la résistance à la compression.
Cependant, un excès de sable peut affaiblir la structure en diminuant la
cohésion entre les particules de ciment et les granulats plus gros
(Neville, 2011). Concrètement, une teneur adéquate en sable améliore le
contact entre la pâte cimentaire et les grains, réduisant la porosité et
favorisant ainsi un meilleur transfert des contraintes. Il est donc
essentiel de trouver un équilibre pour garantir une répartition homogène
des matériaux et optimiser la résistance du béton. Quant à l'étude du
bulletin des laboratoires des ponts et chaussées (1999) intitulée
``Influence du granulat sur la résistance à la compression des bétons'',
elle révèle qu'entre 60 \% et 75 \% de volume total d'agrégats, une
variation de la proportion de granulats fins peut entraîner un écart de
l'ordre de 2 à 3 MPa en résistance à la compression. La raison tient à
la formation d'une couche de pâte cimentaire plus ou moins épaisse selon
la quantité de sables incorporée, conditionnant ainsi la compacité et la
performance mécanique du béton. Enfin, L'âge du béton (Age) se définit
comme la durée écoulée depuis le coulage et le compactage jusqu'à la
réalisation des essais mécaniques, habituellement exprimée en nombre de
jours (1, 2, 7, 28, etc.). Il revêt une grande importance, car plus le
béton mûrit, plus la réaction d'hydratation du ciment se poursuit,
consolidant la microstructure et augmentant de manière significative la
résistance en compression. Plusieurs études, dont celles de Neville
(2011), Mindess et Young (2019), montrent que la résistance du béton
augmente avec le temps en raison du processus d'hydratation du ciment.
La majeure partie du gain de résistance se produit au cours des 28
premiers jours, période pendant laquelle le ciment continue de réagir
avec l'eau pour former une structure solide. Cependant, le taux de
durcissement ralentit après cette période, bien que certaines
formulations, notamment celles contenant du laitier ou des cendres
volantes, puissent encore voir leur résistance s'améliorer au-delà de 90
jours. Selon les observations présentées dans un mémoire de recherche
intitulé ``Impact du superplastifiant sur les propriétés
physico-mécaniques du ciment'' à l'université de Blida 1(2022-2023), la
résistance à la compression connaît une croissance rapide entre 1 et 7
jours, passant de 20 \% de la résistance ultime à près de 70 \% autour
de la première semaine . Typiquement, un saut d'environ 10 MPa (environ
50 \%) est constaté entre 2 et 7 jours. Après ce cap, le rythme de
durcissement ralentit, mais on atteint souvent plus de 90 \% de la
résistance finale à 28 jours.

\subsection{Resulats des travaux}\label{resulats-des-travaux}

Nous présentons ici les résultats obtenus avec le modèle final,
construit à partir des critères AIC/BIC, des résultats de l'analyse
descriptives (notamment l'ACP) et des apports de la littérature.

La variable cement (ciment) est fortement significative avec un effet
positif (coefficient estimé à 0.097). Cela confirme que plus on augmente
la quantité de ciment, plus la résistance à la compression augmente. Ce
résultat est en accord avec la littérature, notamment Mehta et Monteiro
(2014), qui ont montré que le ciment est un facteur clé de la
résistance, surtout dans les premiers jours.

L'interaction age * cement est aussi significative (coefficient de
0.00041). Cela veut dire que l'effet du ciment sur la résistance dépend
du temps : plus le béton vieillit, plus cet effet devient important.

La variable age seule est également significative (0.093). Cela confirme
ce qu'indiquent Neville (2011) et Mindess et Young (2019) : la
résistance du béton augmente avec le temps, surtout durant les 28
premiers jours, grâce à la poursuite du processus d'hydratation du
ciment.

Le blast\_furnace (laitier de haut fourneau) a un effet positif (0.054)
et très significatif. Cela reflète bien son rôle connu : il a peu
d'impact au début, mais renforce le béton progressivement. L'interaction
age * blast\_furnace (0.00089) est aussi significative, ce qui montre
que cet effet s'accentue avec le temps, comme le soulignent les travaux
de Jin et al.~(2003).

Concernant fly\_ash (cendres volantes), son effet seul est légèrement
positif (0.014) mais faiblement significatif (p = 0.10). Par contre,
l'interaction age * fly\_ash est bien significative (0.00093), ce qui
veut dire que les cendres volantes contribuent davantage à la résistance
avec le temps. Cela correspond aux observations dans la littérature qui
indiquent un effet lent mais croissant.

L'eau a été centrée avant d'ajouter le terme au carré, pour éviter les
problèmes de colinéarité entre water et water². Le coefficient de
water\_c est négatif (-0.295), ce qui montre que lorsque la quantité
d'eau augmente, la résistance diminue. Le terme water\_c² est positif
(0.00168), ce qui indique que l'effet de l'eau n'est pas linéaire. Cela
signifie qu'à très faibles ou très fortes doses, l'impact sur la
résistance varie. Ce résultat est cohérent avec la notion de rapport
eau/ciment, souvent citée dans la littérature, où trop ou pas assez
d'eau nuit à la performance du béton.

Le super\_plast (superplastifiant) a un effet positif et significatif
(0.443), ce qui montre qu'il améliore la résistance du béton, surtout à
court terme. L'interaction super\_plast * water\_c (0.01795) est aussi
significative, ce qui veut dire que l'effet du superplastifiant dépend
de la quantité d'eau. Cela rejoint les travaux montrant que le
superplastifiant agit sur la fluidité, mais que son effet combiné avec
l'eau est déterminant.

En résumé, le modèle final contient six variables principales (age,
cement, water, super\_plast, blast\_furnace, fly\_ash) et cinq
interactions significatives. Tous les effets inclus sont cohérents avec
la littérature et les résultats de l'analyse exploratoire.

Sur le plan de la performance, la validation croisée à 10 groupes donne
une erreur moyenne de 109.48 pour le modèle basé uniquement sur les
critères AIC, BIC et Fisher. Avec le modèle final, qui inclut des
interactions et un effet quadratique, cette erreur descend à 64.56. Par
ailleurs, le R² ajusté du modèle final est de 0.7768, ce qui signifie
que le modèle explique environ 78 \% de la variabilité observée dans la
résistance à la compression.

\section{Conclusion}\label{conclusion}

Ce travail avait pour objectif d'identifier les facteurs qui influencent
la résistance du béton à la compression, à partir d'une base de données
expérimentales. Pour cela, nous avons combiné des critères statistiques
(AIC/BIC), les résultats de l'analyse descriptive, ainsi que des
éléments issus de la littérature.

Le modèle final comprend six variables principales, plusieurs
interactions et un effet quadratique de l'eau. Il permet d'expliquer
environ 78 \% de la variabilité de la résistance (R² ajusté = 0.7768),
avec une erreur moyenne de 64.56 en validation croisée à 10 groupes.

Les effets estimés sont globalement en accord avec les connaissances du
domaine. Ils mettent en évidence le rôle important du ciment, de l'eau,
du superplastifiant, du laitier et des cendres volantes, ainsi que des
interactions liées à l'évolution dans le temps et à l'effet non linéaire
de l'eau. Malgré certaines limites sur les résidus (autocorrélation,
hétéroscédasticité, et normalité imparfaite), le modèle offre une base
solide pour analyser et interpréter la résistance du béton à la
compression.

\section{Annexe}\label{annexe}

\subsection{Analyse univariée}\label{analyse-univariuxe9e}

\subsubsection{Cement}\label{cement}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-1-1.pdf}

L'histogramme montre une distribution étalée avec plusieurs pics,
indiquant une variabilité dans les proportions de ciment utilisées. Les
valeurs les plus courantes se situent entre 100 et 400 kg/m³. Cette
répartition suggère que différentes formulations de béton nécessitent
des proportions de ciment variées, influençant potentiellement la
résistance finale du béton.

\subsubsection{Blast Furnace Slag}\label{blast-furnace-slag}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-2-1.pdf}

La majorité des valeurs sont proches de zéro, suggérant que le blast
furnace slag est rarement utilisé en grande quantité. Cependant,
quelques observations montrent une présence significative de ce
composant, ce qui pourrait indiquer des formulations spécifiques
cherchant à améliorer certaines propriétés du béton, comme la durabilité
ou la résistance aux sulfates.

\subsubsection{Fly Ash}\label{fly-ash}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-3-1.pdf}

La distribution est fortement biaisée vers zéro, montrant que le fly ash
est peu utilisé dans la majorité des échantillons. Seules quelques
observations présentent des valeurs plus élevées, ce qui indique que cet
additif est employé dans des mélanges spécifiques, probablement pour
optimiser la maniabilité ou réduire les coûts en substituant une partie
du cement.

\subsubsection{Water}\label{water}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-4-1.pdf}

La répartition est relativement normale avec un pic autour de 200 kg/m³,
ce qui indique une quantité d'eau standardisée dans la plupart des
mélanges. Une consommation d'eau bien contrôlée est essentielle pour
assurer une bonne hydratation du ciment et éviter une porosité excessive
pouvant affaiblir le matériau.

\subsubsection{Superplasticizer}\label{superplasticizer}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-5-1.pdf}

La plupart des valeurs sont proches de zéro, ce qui signifie que le
superplasticizer est peu utilisé dans de nombreux échantillons.
Cependant, certaines observations indiquent une utilisation plus
importante, ce qui peut être lié à des mélanges nécessitant une
meilleure fluidité tout en réduisant le rapport water/cement pour
maximiser la résistance finale.

\subsubsection{Coarse Aggregate}\label{coarse-aggregate}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-6-1.pdf}

Le coarse aggregate suit une distribution centrée autour de 950-1000
kg/m³, ce qui montre une standardisation dans son utilisation. La
présence d'une quantité relativement constante de coarse aggregate est
essentielle pour garantir la stabilité et la résistance mécanique du
béton tout en minimisant la fissuration.

\subsubsection{Fine Aggregate}\label{fine-aggregate}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-7-1.pdf}

La distribution est également centrée autour de 750-800 kg/m³, suggérant
une utilisation homogène du fine aggregate dans les différents mélanges
de béton. Une quantité bien maîtrisée de fine aggregate améliore la
compacité du béton et influe sur sa capacité de mise en œuvre et son
imperméabilité.

\subsubsection{Age}\label{age}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-8-1.pdf}

L'âge du béton est majoritairement faible, avec une concentration autour
de 28 jours. Quelques échantillons présentent des âges plus avancés,
jusqu'à un an. Cela reflète l'importance de la période de cure du béton,
puisque la résistance continue d'augmenter avec le temps grâce à
l'hydratation prolongée du cement.

\subsubsection{Concrete Compressive
Strength}\label{concrete-compressive-strength}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-9-1.pdf}

La concrete compressive strength suit une distribution proche d'une loi
normale, avec un pic autour de 40 MPa. Cela indique une variabilité
contrôlée de la résistance du béton. La concrete compressive strength
étant un paramètre clé, cette distribution montre que la plupart des
mélanges atteignent une performance attendue, bien qu'il existe des
échantillons avec des valeurs plus élevées ou plus faibles en fonction
des formulations utilisées.

\subsubsection{Fig 10 : Détection des valeurs aberrantes
(Boxplots)}\label{fig-10-duxe9tection-des-valeurs-aberrantes-boxplots}

\includegraphics{rmd_final_files/figure-latex/boxplots_outliers-1.pdf}

\subsection{Analyse bivariee}\label{analyse-bivariee}

\subsubsection{Matrice de correlation}\label{matrice-de-correlation}

\begin{verbatim}
##                            cement blast_furnace      fly_ash       water
## cement                 1.00000000   -0.27519344 -0.397475440 -0.08154361
## blast_furnace         -0.27519344    1.00000000 -0.323569468  0.10728594
## fly_ash               -0.39747544   -0.32356947  1.000000000 -0.25704400
## water                 -0.08154361    0.10728594 -0.257043997  1.00000000
## super_plast            0.09277137    0.04337574  0.377339559 -0.65746444
## coarse                -0.10935604   -0.28399823 -0.009976788 -0.18231167
## fine_aggr             -0.22272017   -0.28159326  0.079076351 -0.45063498
## age                    0.08194726   -0.04424580 -0.154370165  0.27760443
## y_concrete_compresive  0.49783272    0.13482445 -0.105753348 -0.28961348
##                       super_plast       coarse   fine_aggr          age
## cement                 0.09277137 -0.109356039 -0.22272017  0.081947264
## blast_furnace          0.04337574 -0.283998230 -0.28159326 -0.044245801
## fly_ash                0.37733956 -0.009976788  0.07907635 -0.154370165
## water                 -0.65746444 -0.182311668 -0.45063498  0.277604429
## super_plast            1.00000000 -0.266302755  0.22250149 -0.192716518
## coarse                -0.26630276  1.000000000 -0.17850575 -0.003015507
## fine_aggr              0.22250149 -0.178505755  1.00000000 -0.156094049
## age                   -0.19271652 -0.003015507 -0.15609405  1.000000000
## y_concrete_compresive  0.36610230 -0.164927821 -0.16724896  0.328876976
##                       y_concrete_compresive
## cement                            0.4978327
## blast_furnace                     0.1348244
## fly_ash                          -0.1057533
## water                            -0.2896135
## super_plast                       0.3661023
## coarse                           -0.1649278
## fine_aggr                        -0.1672490
## age                               0.3288770
## y_concrete_compresive             1.0000000
\end{verbatim}

\begin{center}\includegraphics{rmd_final_files/figure-latex/corr_y-1} \end{center}

La matrice de corrélation en annexe va nous aider à voir les différents
liens de corrélation potentiels entre nos variables. Dans cette partie,
nous allons étudier et essayer de trouver les couples de variables
significativement dépendants. Il est important de trouver tous les
couples liés afin d'expliquer de manière optimale comment les variables
de notre base peuvent influer sur la résistance à la compression du
béton.

\subsubsection{Quantité de ciment et résistance du
béton.}\label{quantituxe9-de-ciment-et-ruxe9sistance-du-buxe9ton.}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-10-1} \end{center}

Nous allons ici examiner si la quantité de ciment utilisée pour créer le
béton est significativement reliée à la résistance à la compression du
béton. En effet, nous pouvons d'abord observer la distribution de ces
deux variables à l'aide du graphique ci-dessous :

Cette visualisation des données nous donne une première impression du
lien potentiel entre ces deux variables. En étudiant plus précisément
ces deux variables avec un test de corrélation de Pearson, on se rend
compte qu'il y a un lien significatif : ces deux variables sont
positivement liées.

On peut alors dire que plus la quantité de ciment utilisée pour la
fabrication du béton est grande, plus la résistance à la compression de
ce béton sera importante. Le test final a donné un coefficient de
corrélation \(\rho\) de Pearson égal à \textbf{0,5} (annexe), ce qui
indique un lien relativement fort et non négligeable. Ainsi, une
fabrication de béton comprenant une grande quantité de ciment
favoriserait grandement sa résistance à la compression.

\subsubsection{Additif chimique et eau.}\label{additif-chimique-et-eau.}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-11-1} \end{center}

Dans le processus de fabrication du béton, il est parfois nécessaire
d'ajouter un additif chimique pour améliorer sa fluidité et sa
maniabilité. La réflexion porte ici sur la corrélation entre l'ajout de
cet additif chimique et la quantité d'eau utilisée pour la fabrication :
y aurait-il un quelconque lien entre ces deux variables ?

Pour ce faire, il semble juste d'examiner les différents ajouts
d'additif en fonction de la quantité d'eau utilisée pour chaque béton.
Le graphique ci-dessous illustre cette relation, et nous pouvons
aisément supposer qu'il existe une corrélation entre ces deux variables.
En effet, dans l'ensemble, on remarque une diminution de l'ajout
d'additif lorsque la quantité d'eau augmente.

Pour avoir une certitude, nous effectuons alors un test de corrélation
de Kendall, qui nous indique, premièrement, qu'il existe un lien
significatif entre ces deux variables et, deuxièmement, que le
coefficient de corrélation \(\tau\) étant de \textbf{-0.53} (annexe), la
négativité de la liaison est prouvée.

En clair, plus la quantité d'eau utilisée pour la fabrication du béton
est importante, moins d'additif chimique a été ajouté lors de cette
fabrication. Ce lien fort nous aidera dans la suite de notre étude.

\subsubsection{L'age, une variable
importante.}\label{lage-une-variable-importante.}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-12-1} \end{center}

Il serait tout à fait naturel de penser que l'âge ait une quelconque
importance sur la résistance à la compression du béton. En effet,
l'imaginaire collectif nous amène d'abord à penser que ce béton, en
conséquence de l'âge, deviendrait de plus en plus fragile et, de ce
fait, moins résistant à la compression. Notre hypothèse serait alors de
dire que l'âge est négativement lié à la résistance à la compression du
béton, \(i.e.\), plus l'âge augmente, moins le béton est résistant.

Dans un premier temps, l'observation de la distribution du temps par
rapport à la compression nous aiderait à confirmer ou infirmer
l'hypothèse de cette partie. Voyons le graphique ci-dessous.

Cette première visualisation ne nous permet pas de déterminer s'il
existe réellement un lien entre ces deux variables. Une exagération
pourrait peut-être nous amener à supposer l'existence d'une relation
quadratique entre elles, mais cette hypothèse ne peut être vérifiée dans
cette partie.

En conséquence, il est nécessaire de réaliser un test de corrélation.

Le test effectué nous permet de constater que notre hypothèse est
infirmée, car il existe bien un lien significatif entre ces deux
variables, et la corrélation indique que ce lien est positif. Cette
corrélation est positive mais modérée, avec un coefficient de Kendall
\(\tau\) de 0,449 (voir annexe). Les valeurs croissent significativement
ensemble, bien que certaines exceptions subsistent.

\subsubsection{La resistance à la compression du béton peut-elle
s'expliquer grâce au laitier de haut fournaux
?}\label{la-resistance-uxe0-la-compression-du-buxe9ton-peut-elle-sexpliquer-gruxe2ce-au-laitier-de-haut-fournaux}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-14-1} \end{center}

On examine ici la relation entre le laitier de haut fourneau et la
résistance à la compression du béton :

Ce graphique ne suggère aucun lien de corrélation entre la quantité de
laitier de haut fourneau et la résistance à la compression du béton, mis
à part une légère baisse de la résistance du béton lorsque la quantité
de laitier de haut fourneau augmente. Afin de détecter une potentielle
relation de dépendance, il pourrait être judicieux d'effectuer un test
de corrélation de Spearman.

En effet, ce test nous fournit une p-value inférieure à 0.05 et un
coefficient \(\rho\) de 0.16. Ces valeurs indiquent qu'il existe bien un
lien significatif positif entre ces deux variables, mais cette
corrélation reste faible compte tenu de la proximité de \(\rho\) avec
zéro.

\subsubsection{Les cendres volantes peuvent-elles expliquer la
resistance du béton
?}\label{les-cendres-volantes-peuvent-elles-expliquer-la-resistance-du-buxe9ton}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-16-1} \end{center}

Pour tenter de répondre à cette question, on peut d'abord examiner la
distribution de la quantité de cendres volantes en fonction de la
résistance à la compression du béton.

La représentation de la distribution de notre variable à expliquer par
rapport à la variable explicative suggère une légère corrélation
linéaire négative. On pourrait alors en déduire que plus la quantité de
cendres volantes augmente, moins le béton résiste à la compression.

Pour s'assurer de la justesse de cette analyse, nous réalisons un test
de corrélation de Spearman, qui met en évidence un lien significatif
entre ces deux variables. Comme indiqué dans notre interprétation, ce
lien est négatif, avec un coefficient \(\rho\) de -0.19, indiquant ainsi
une corrélation faible mais non négligeable.

\subsubsection{L'eau, un facteur de résistance
?}\label{leau-un-facteur-de-ruxe9sistance}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-18-1} \end{center}

Dans l'imaginaire collectif, il est tout à fait logique de penser que si
l'on ajoute de l'eau lors de la création du béton, celui-ci sera moins
résistant que si l'on ne le fait pas. Cependant, il est indispensable
d'incorporer une certaine quantité d'eau. L'objectif est donc de trouver
un juste milieu dans cette quantité. Examinons d'abord la distribution
de la résistance des bétons par rapport à leur résistance à la
compression :

Comme dans la partie précédente, le graphique est relativement
désordonné, mais on peut tout de même y relever une légère dépendance
négative, comme mentionné dans l'introduction de l'étude de cette
dépendance. Pour être sûr de nos analyses, il serait nécessaire
d'effectuer un test de corrélation de Spearman.

Le résultat de ce test indique qu'il existe bien une corrélation avec un
coefficient de corrélation de -0.31, ce qui montre un lien négatif non
négligeable entre ces deux variables.

En conclusion, moins il y a d'eau dans la création du béton, plus
celui-ci sera résistant. Cependant, les points situés à l'extrémité
gauche du graphique suggèrent qu'un minimum d'eau est tout de même
nécessaire pour que le béton atteigne une résistance suffisante.

\subsubsection{Superplasticité et
Résistance}\label{superplasticituxe9-et-ruxe9sistance}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-20-1} \end{center}

Le superplastifiant, utilisé dans les mélanges de béton, joue un rôle
essentiel en améliorant la fluidité du béton sans ajout d'eau
supplémentaire. Ce composant chimique permet d'augmenter la densité du
béton, contribuant ainsi à une meilleure résistance à la compression.

Visuellement, le graphique ne permet pas de tirer de conclusions claires
sur la relation entre la quantité de superplastifiant et la résistance à
la compression du béton. Bien que la tendance semble indiquer une
augmentation initiale de la résistance avec l'ajout de superplastifiant,
la distribution des points reste dispersée. De plus, la présence de
nombreux points proches du début de la courbe rend difficile
l'identification d'une tendance nette.

Le test de Kendall révèle une corrélation positive modérée (tau = 0.249)
entre la quantité de superplastifiant et la résistance à la compression
du béton. Cette corrélation est significative, comme en témoigne la
p-value extrêmement faible, bien inférieure à 0.05. Cela suggère que, de
manière générale, une augmentation de la quantité de superplastifiant
dans le mélange de béton pourrait être associée à une amélioration de sa
résistance à la compression.

\subsubsection{Granulats grossiers et résistance à la
compression}\label{granulats-grossiers-et-ruxe9sistance-uxe0-la-compression}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-22-1} \end{center}

Les granulats grossiers, qui comprennent des particules de grande taille
comme des graviers ou des pierres concassées, contribuent à la
résistance à la compression du béton en réduisant les vides dans le
mélange, augmentant ainsi sa compacité.

Le graphique représente la relation entre les granulats grossiers et la
résistance à la compression du béton. La répartition des données semble
dispersée. On peut néanmoins observer un lien quadratique entre ces deux
variables, mais il est difficile d'en tirer une conclusion plus
approfondie.

Le test de corrélation de Kendall a donné un coefficient tau de -0.124.
Bien que la p-value soit très faible (3.318e-09), ce faible tau indique
une relation négative mais modérée. Cela signifie qu'il existe bien une
certaine corrélation entre ces deux variables.

\subsubsection{Fig 20 : Relation entre granulats fins et la resistance à
la
compression}\label{fig-20-relation-entre-granulats-fins-et-la-resistance-uxe0-la-compression}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-24-1} \end{center}

test corrrelation entre variable à expliquer et \texttt{cement}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor.test}\NormalTok{(bdd}\SpecialCharTok{$}\NormalTok{cement, bdd}\SpecialCharTok{$}\NormalTok{y\_concrete\_compresive, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  bdd$cement and bdd$y_concrete_compresive
## t = 18.405, df = 1028, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4504473 0.5424213
## sample estimates:
##       cor 
## 0.4978327
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#test de pearson car ont une distribution pseudo{-}normale}
\end{Highlighting}
\end{Shaded}

test de correlation entre variable \texttt{water} et
\texttt{SuperPlasticizer}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor.test}\NormalTok{(bdd}\SpecialCharTok{$}\NormalTok{water, bdd}\SpecialCharTok{$}\NormalTok{super\_plast, }\AttributeTok{method =} \StringTok{"kendall"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Kendall's rank correlation tau
## 
## data:  bdd$water and bdd$super_plast
## z = -23.914, p-value < 2.2e-16
## alternative hypothesis: true tau is not equal to 0
## sample estimates:
##       tau 
## -0.528651
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#test de Kendall car n\textquotesingle{}ont pas de distribution pseudo{-} normale}
\end{Highlighting}
\end{Shaded}

test de correlation entre variable \texttt{water} et \texttt{y}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor.test}\NormalTok{(bdd}\SpecialCharTok{$}\NormalTok{age, bdd}\SpecialCharTok{$}\NormalTok{y\_concrete\_compresive, }\AttributeTok{method =} \StringTok{"kendall"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Kendall's rank correlation tau
## 
## data:  bdd$age and bdd$y_concrete_compresive
## z = 19.826, p-value < 2.2e-16
## alternative hypothesis: true tau is not equal to 0
## sample estimates:
##       tau 
## 0.4490164
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#test de Kendall car n\textquotesingle{}ont pas de distribution pseudo{-} normale}
\end{Highlighting}
\end{Shaded}

\subsection{Ingénierie des données}\label{inguxe9nierie-des-donnuxe9es}

La base de données contient \textbf{1030 observations et 9 variables
numériques} initialement. Dans cette partie, nous préparons les données
pour garantir leur qualité et leur pertinence. Cette étape comprend deux
étapes principales :

\begin{itemize}
\tightlist
\item
  \textbf{Détection et traitement des valeurs aberrantes} à l'aide de
  boxplots.\\
\item
  \textbf{Analyse des corrélations} pour éviter la redondance des
  variables.
\end{itemize}

\subsubsection{Détection des valeurs
aberrantes}\label{duxe9tection-des-valeurs-aberrantes}

Les valeurs aberrantes peuvent fausser l'analyse et influencer la
modélisation. Les \textbf{boxplots} (voir
\hyperref[duxe9tection-des-valeurs-aberrantes-boxplots]{Analyse
univariée}) permettent d'identifier des observations extrêmes.

Certaines variables comme \textbf{Cement, Fly Ash} et \textbf{Coarse
Aggregate} ont une distribution homogène et sont conservées sans
modification.

La variable \textbf{Water} présente quelques valeurs extrêmes. Plutôt
que de les exclure, nous analysons leur impact.

La variable \textbf{Superplasticizer} contient des valeurs très
éloignées du reste des observations. Pour éviter toute influence
excessive, ces valeurs extrêmes sont exclues en utilisant la règle des
1.5*IQR :

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calcul des seuils avec la règle des 1.5*IQR pour Superplasticizer}
\NormalTok{Q1\_sp }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(bdd}\SpecialCharTok{$}\NormalTok{super\_plast, }\FloatTok{0.25}\NormalTok{)}
\NormalTok{Q3\_sp }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(bdd}\SpecialCharTok{$}\NormalTok{super\_plast, }\FloatTok{0.75}\NormalTok{)}
\NormalTok{IQR\_sp }\OtherTok{\textless{}{-}}\NormalTok{ Q3\_sp }\SpecialCharTok{{-}}\NormalTok{ Q1\_sp}

\NormalTok{seuil\_sup\_sp }\OtherTok{\textless{}{-}}\NormalTok{ Q3\_sp }\SpecialCharTok{+} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ IQR\_sp}

\CommentTok{\# Filtrer les valeurs aberrantes pour Superplasticizer}
\NormalTok{bdd\_ing }\OtherTok{\textless{}{-}}\NormalTok{ bdd }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(super\_plast }\SpecialCharTok{\textless{}=}\NormalTok{ seuil\_sup\_sp)}
\end{Highlighting}
\end{Shaded}

Concernant \textbf{Blast Furnace Slag}, quelques valeurs sont élevées
mais restent plausibles. Elles sont conservées sans modification.

La variable \textbf{Age} présente des valeurs extrêmes qu'il faut
filtrer. En utilisant la règle des 1.5*IQR, nous identifions les
observations anormalement élevées et les supprimons pour assurer une
meilleure cohérence des données :

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calcul des seuils avec la règle des 1.5*IQR pour Age}
\NormalTok{Q1\_age }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(bdd\_ing}\SpecialCharTok{$}\NormalTok{age, }\FloatTok{0.25}\NormalTok{)}
\NormalTok{Q3\_age }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(bdd\_ing}\SpecialCharTok{$}\NormalTok{age, }\FloatTok{0.75}\NormalTok{)}
\NormalTok{IQR\_age }\OtherTok{\textless{}{-}}\NormalTok{ Q3\_age }\SpecialCharTok{{-}}\NormalTok{ Q1\_age}

\NormalTok{seuil\_sup\_age }\OtherTok{\textless{}{-}}\NormalTok{ Q3\_age }\SpecialCharTok{+} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ IQR\_age}

\CommentTok{\# Filtrer les valeurs aberrantes pour Age}
\NormalTok{bdd\_ing }\OtherTok{\textless{}{-}}\NormalTok{ bdd\_ing }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(age }\SpecialCharTok{\textless{}=}\NormalTok{ seuil\_sup\_age)}
\NormalTok{bdd\_final }\OtherTok{\textless{}{-}}\NormalTok{ bdd\_ing}
\end{Highlighting}
\end{Shaded}

\subsubsection{Analyse des
corrélations}\label{analyse-des-corruxe9lations}

L'objectif est d'identifier les variables fortement corrélées entre
elles pour éviter la \textbf{multicolinéarité} dans le modèle.

La \textbf{matrice de corrélation} (voir
\hyperref[matrice-de-correlation]{Analyse bivariée}) permet d'observer
les liens entre les différentes variables.

La variable cible \textbf{y\_concrete\_compresive} présente des
corrélations notables avec certaines variables explicatives : -
\textbf{cement (0.50)} : Forte corrélation positive, suggérant une
relation directe entre la quantité de ciment et la résistance à la
compression.\\
- \textbf{cater (-0.29)} : Corrélation négative, ce qui est cohérent
avec l'hypothèse qu'un excès d'eau diminue la résistance du béton.\\
- \textbf{super\_plast (0.37)} : Corrélation indiquant que cet additif
pourrait améliorer la résistance du béton.\\
- \textbf{age (0.33)} : Relation positive, confirmant que la résistance
augmente avec le temps.

Certaines variables explicatives montrent également des
\textbf{corrélations importantes entre elles}, ce qui peut poser
problème : - \textbf{water et super\_plast (-0.65)} : Corrélation
négative forte, ce qui est logique car le superplastifiant permet de
réduire la quantité d'eau nécessaire.\\
- \textbf{blast\_furnace et fly\_ash (-0.32)} : Corrélation négative
modérée, indiquant que ces composants sont parfois utilisés en
substitution l'un de l'autre.

Nous devons \textbf{évaluer l'impact de ces relations dans le modèle}.
Si deux variables sont trop fortement corrélées, l'une d'elles pourrait
être supprimée pour éviter des problèmes de multicolinéarité.

Ces observations pourront nous aider lors de la sélection des variables
dans la prochaine étape.

\subsubsection{Synthèse de l'Ingénierie des
Données}\label{synthuxe8se-de-linguxe9nierie-des-donnuxe9es}

Après le traitement des valeurs aberrantes et l'analyse des
corrélations, la base de données passe de \textbf{1030 à 961
observations}.

Les valeurs extrêmes des variables \textbf{Age} et
\textbf{Superplasticizer} ont été supprimées en appliquant la règle des
1.5*IQR, garantissant une meilleure cohérence des données.

L'analyse des corrélations a révélé des relations notables entre
plusieurs variables, notamment une forte corrélation entre \textbf{Water
et Superplasticizer (-0.65)} et un lien important entre \textbf{Cement
et la résistance à la compression (0.50)}.

\subsection{Analyse multivariée}\label{analyse-multivariuxe9e}

Dans cette partie, nous allons étudier l'ensemble des variables en
utilisant une analyse en composantes principales (ACP). La variable à
expliquer (``y\_concrete\_compresive'') est également considérée comme
active, aux côtés des huit autres variables explicatives.

\subsection{Histogramme des valeurs
propres}\label{histogramme-des-valeurs-propres}

\begin{verbatim}
## Warning: package 'FactoMineR' was built under R version 4.4.2
\end{verbatim}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-30-1} \end{center}

Le graphique illustre l'histogramme des valeurs propres issu de l'ACP,
permettant d'identifier le nombre d'axes principaux à retenir.

\begin{itemize}
\tightlist
\item
  Le premier axe capte une part importante de la variance totale.
\item
  Le deuxième axe conserve également une proportion significative
  d'information.
\item
  Le troisième axe ajoute un complément notable de variance.
\item
  À partir du quatrième axe, la contribution devient plus marginale.
\end{itemize}

En appliquant la \textbf{règle du coude}, il est pertinent de retenir
les \textbf{trois premiers axes} pour l'analyse.

\subsection{Analyse sur les 2 Premiers
Axes}\label{analyse-sur-les-2-premiers-axes}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-31-1} \end{center}

Le cercle de corrélation met en évidence les relations entre les
variables étudiées, projetées sur les deux premiers axes principaux de
l'ACP. Ces axes capturent ensemble \textbf{45,67 \%} de la variance
totale des données (\textbf{25,02 \% pour Dim 1 et 20,64 \% pour Dim
2}).

\subsubsection{Interprétation du Premier Axe (Dim 1 : 25,02
\%)}\label{interpruxe9tation-du-premier-axe-dim-1-2502}

Le premier axe distingue \textbf{les formulations riches en eau
(\texttt{water})} de celles utilisant \textbf{des superplastifiants
(\texttt{super\_plast})}.

\begin{itemize}
\tightlist
\item
  \texttt{water} (28,20 \% de contribution, cos² = 0.62) est la deuxième
  variable la plus influente sur Dim 1. Son orientation négative indique
  qu'une teneur élevée en eau tend à être associée à une baisse de la
  résistance à la compression.
\item
  \texttt{super\_plast} (30,77 \% de contribution, cos² = 0.69) est
  projetée dans la direction opposée à \texttt{water}, traduisant son
  rôle de réduction du besoin en eau, favorisant ainsi la résistance.
  c'est la variable la plus influente sur cet axe.
\item
  \texttt{fly\_ash} (7,3 \% de contribution, cos² = 0.16) et
  \texttt{fine\_aggr} (4,86\% de contribution, cos² = 0.11) ne sont pas
  bien projetées sur cet axe.
\item
  \texttt{age} (5,57 \% de contribution, cos² = 0.13) est aussi bien
  représenté sur Dim 1, confirmant que la résistance du béton augmente
  avec le temps de durcissement.
\item
  \texttt{y\_concrete\_compresive} (19,17 \% de contribution, cos² =
  0.43) est bien projetée sur Dim 1 ainsi que son cos² indique qu'elle
  est très bien representée sur cet axe.
\end{itemize}

\subsubsection{Interprétation du Deuxième Axe (Dim 2 : 21,52
\%)}\label{interpruxe9tation-du-deuxiuxe8me-axe-dim-2-2152}

Le deuxième axe distingue \textbf{les formulations riches en ciment
(\texttt{cement}) et associées à une plus grande résistance
(\texttt{y\_concrete\_compresive})} des formulations utilisant
\textbf{une proportion plus élevée des cendres volantes (`fly\_ash') et
les granulats fins (\texttt{fine\_aggr})}.

\begin{itemize}
\tightlist
\item
  \texttt{y\_concrete\_compresive} (24.70 \% de contribution, cos² =
  0.45) est la variable la plus influente sur Dim 2. Cela signifie que
  la résistance à la compression est fortement expliquée par cette
  dimension.
\item
  \texttt{cement} (21.78 \% de contribution, cos² = 0.40) est bien
  représentée sur Dim 2, indiquant que la quantité de ciment influence
  fortement la résistance mécanique. -fly\_ash (20.39\% de contribution
  et cos² = 0.38) et fin\_aggr (13.01\% de contribution et cos² = 0,24)
  contribuent plus sur cet axe que sur le premier et elles sont très
  bien representées sur cet axe contrairement au premier axe, suggérant
  que ces composants influencent la résistence du béton de la meme façon
  puisque les fleches de ces deux variables sont confondues.
\item
  \texttt{coarse} (5.05 \% de contribution, cos² = 0.10) et
  blast\_furnace (10.61\% de contribution et un cos² = 0.10) ne sont pas
  bien projetées sur cet axe et contribue faiblement à al construction
  de cette dimension. Elles pourraient etre expliquées par le troisième
  axe.
\end{itemize}

\subsubsection{Contribution des
variables}\label{contribution-des-variables}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Tableau des contributions des variables}
\FunctionTok{par}\NormalTok{(}\AttributeTok{cex =} \FloatTok{0.65}\NormalTok{)}
\NormalTok{contrib\_var }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(res\_pca}\SpecialCharTok{$}\NormalTok{var}\SpecialCharTok{$}\NormalTok{contrib)}
\FunctionTok{print}\NormalTok{(contrib\_var)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                            Dim.1      Dim.2      Dim.3      Dim.4      Dim.5
## cement                 1.8570924 21.8162521 19.4630539 17.0024498  0.3034758
## blast_furnace          1.3854568 10.6144114 38.1264598  0.8844007  4.7645646
## fly_ash                7.2754889 20.3973975  1.3084478  9.8815857  4.0570219
## water                 28.2000179  2.1202816  1.4847945  2.0723167  4.4435413
## super_plast           30.7756668  0.2472336  6.2022982  0.9015953  8.4701606
## coarse                 0.8939835  3.4632950 32.5054492 12.5162699 10.6005496
## fine_aggr              4.8648268 13.0123250  0.2499000 13.1394718 39.0454823
## age                    5.5749786  4.1403732  0.4309223 40.7207759 28.1887145
## y_concrete_compresive 19.1724883 24.1884306  0.2286743  2.8811343  0.1264894
\end{verbatim}

\subsubsection{\texorpdfstring{Tableau des \(cos^2\) des variables
sur}{Tableau des cos\^{}2 des variables sur}}\label{tableau-des-cos2-des-variables-sur}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Tableau des cos² des variables}
\FunctionTok{par}\NormalTok{(}\AttributeTok{cex =} \FloatTok{0.65}\NormalTok{)}
\NormalTok{cos2\_var }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(res\_pca}\SpecialCharTok{$}\NormalTok{var}\SpecialCharTok{$}\NormalTok{cos2)}
\FunctionTok{print}\NormalTok{(cos2\_var)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                            Dim.1       Dim.2       Dim.3      Dim.4       Dim.5
## cement                0.04181872 0.405352873 0.271676732 0.19539670 0.003132659
## blast_furnace         0.03119825 0.197219125 0.532191509 0.01016377 0.049182696
## fly_ash               0.16383224 0.378990105 0.018264082 0.11356182 0.041879015
## water                 0.63501880 0.039395503 0.020725633 0.02381562 0.045868900
## super_plast           0.69301824 0.004593679 0.086575320 0.01036137 0.087434082
## coarse                0.02013106 0.064349119 0.453730143 0.14384032 0.109425235
## fine_aggr             0.10954803 0.241773118 0.003488251 0.15100232 0.403050903
## age                   0.12553950 0.076929445 0.006015067 0.46797404 0.290980829
## y_concrete_compresive 0.43173343 0.449428700 0.003191970 0.03311077 0.001305699
\end{verbatim}

\subsubsection{Interprétation du Troisième
Axe}\label{interpruxe9tation-du-troisiuxe8me-axe}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot.PCA}\NormalTok{(}
\NormalTok{    res\_pca,}
    \AttributeTok{axes =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{),             }\CommentTok{\# On se concentre sur les axes 2 et 3}
    \AttributeTok{choix =} \StringTok{"var"}\NormalTok{,              }\CommentTok{\# Afficher les variables dans le plan factoriel}
    \AttributeTok{col.var =} \StringTok{"\#4B0000"}\NormalTok{,        }\CommentTok{\# Couleur des variables alignée au style}
    \AttributeTok{col.quanti.sup =} \StringTok{"\#0000FF"}\NormalTok{, }\CommentTok{\# Couleur pour la variable quantitative supplémentaire}
    \AttributeTok{label =} \StringTok{"all"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{""}\NormalTok{,}
    \AttributeTok{addgrid.col =} \StringTok{"\#DDB688"}     \CommentTok{\# Couleur de la grille}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-34-1} \end{center}

Dim(1-3) : 40.5\% \% de la Variance Totale

Le troisième axe distingue \textbf{les formulations riches en laitier du
haut fourneau (\texttt{blast\_frunace}) et associées à une plus grande
résistance (\texttt{y\_concrete\_compresive})} des formulations
utilisant \textbf{une proportion plus élevée des granulats grossiers
(\texttt{Coarse}) et du ciment (\texttt{Cement})}. ces deux axes
representent 40.5\% de la varaince totale.

-\texttt{blast\_frunace} (38.12\% de contribution et cos² = 0.53)
constitue la variable la plus influente et impacte positivement la
resistance à la compression du beton. une hausse du laitier haut
fourneau renforce la resistance.

-\texttt{Coarse} (avec 32.5\% de contribution et cos² = 0.45) represente
la deuxieme variable la plus importante et contribue en grande partie à
la construction de cet axe. elle est projetée dans la direction opposée
à \texttt{blast\_frunace} et \texttt{y\_concrete\_compresive}, suggérant
que les formulations contenant une proportion élevée de granulats
grossiers sont associées à une résistance plus faible.

\begin{itemize}
\tightlist
\item
  Enfin, nous avons la variable \texttt{Cement} qui est egalement bien
  representée (cos² = 0.27) et contribue à la hauteur de 19.46\% à la
  construction de cet axe.
\end{itemize}

\subsubsection{Interpretation PCA sur la dimension
2-3}\label{interpretation-pca-sur-la-dimension-2-3}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Représentation des variables sur le plan factoriel (axes 1 et 3)}
\FunctionTok{plot.PCA}\NormalTok{(}
\NormalTok{  res\_pca,}
  \AttributeTok{axes =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{),             }\CommentTok{\# On se concentre sur les 2 premiers axes}
  \AttributeTok{choix =} \StringTok{"var"}\NormalTok{,              }\CommentTok{\# Afficher les variables dans le plan factoriel}
  \AttributeTok{col.var =} \StringTok{"\#4B0000"}\NormalTok{,        }\CommentTok{\# Couleur des variables alignée au style}
  \AttributeTok{col.quanti.sup =} \StringTok{"\#0000FF"}\NormalTok{, }\CommentTok{\# Couleur pour la variable quantitative supplémentaire}
  \AttributeTok{label =} \StringTok{"all"}\NormalTok{,}
  \AttributeTok{title =} \StringTok{""}\NormalTok{,}
  \AttributeTok{addgrid.col =} \StringTok{"\#DDB688"}     \CommentTok{\# Couleur de la grille}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-35-1} \end{center}

Dim(2-3) : 36.14 \% de la Variance Totale (Voir annexe : Partie 22)

Le troisième axe distingue \textbf{les formulations riches en laitier du
haut fourneau (\texttt{blast\_frunace}) et associées à une plus grande
résistance (\texttt{y\_concrete\_compresive})} des formulations
utilisant \textbf{une proportion plus élevée des granulats grossiers
(\texttt{Coarse}) et du ciment (\texttt{Cement})}. ces deux axes
representent 40.5\% de la varaince totale.

nous remarquons la meme conclusion que l'analyse des axes 1-3. Retenons
que la variable age (\texttt{age}) n'est pas bien representée sur les
trois premiers axes mais pon remmarque qu'elle est très bien representée
sur le quatrième axe avec 40.72\% de contribution et 0.46 comme qualité
de representation. compte tenu de la mauvaise representation de la
variable cible sur cet axe, nous pouvons conclure que l'age n'influence
pas de manière significative la resistance à la compression du beton.

Cette ACP met en évidence trois dimensions principales dans la
composition du béton :

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Axe 1 (Dim 1)} : Opposition entre l'eau et les
  superplastifiants.
\item
  \textbf{Axe 2 (Dim 2)} : Opposition entre ciment et cendres volantes,
  granulats fins.
\item
  \textbf{Axe 3 (Dim 3)} : Opposition entre laitier du haut fourneau et
  granulats grossiers, ciment
\end{enumerate}

\subsection{Implications pour la Modélisation de la Résistance du
Béton}\label{implications-pour-la-moduxe9lisation-de-la-ruxe9sistance-du-buxe9ton}

\begin{itemize}
\tightlist
\item
  L'opposition entre \texttt{water} et \texttt{super\_plast} sur Dim 1
  indique qu'un \textbf{terme d'interaction} entre ces deux variables
  pourrait être testé dans le modèle linéaire.
\item
  \texttt{fine\_aggr} et \texttt{fly\_ash} étant bien projetées sur Dim
  2, leurs interactions avec \texttt{cement} pourraient être pertinentes
  pour examiner leurs effets combinés sur la compacité et la résistance.
\item
  \texttt{age} étant bien représentée sur Dim 4, une interaction avec
  \texttt{Cement} pourrait être étudiée pour voir comment l'évolution du
  béton avec le temps est influencée par le ciment.
\item
  \texttt{y\_concrete\_compresive} étant principalement projeté sur Dim
  2, un modèle linéaire devrait inclure \textbf{\texttt{cement},
  \texttt{blast\_furnace}, \texttt{fly\_ash}, \texttt{fine\_aggr}} comme
  facteurs explicatifs car d'après nos analyses, ce sont les variables
  succeptibles d'influer sur la resistance à la compression.
\item
  L'opposition entre \texttt{coarse} et \texttt{super\_blast} sur Dim 2
  suggère qu'un effet combiné de ces deux variables pourrait influencer
  la résistance mécanique.
\end{itemize}

\newpage

\section{Modélisation linéaire}\label{moduxe9lisation-linuxe9aire}

Dans cette section, nous nous concentrons sur l'application de la
régression linéaire pour modéliser la relation entre la résistance à la
compression du béton et ses différentes variables explicatives. Cette
approche permet de comprendre l'impact de chaque variable exogène sur la
variable cible, d'identifier les relations significatives ainsi que
d'évaluer leur pertinence statistique et les hypothèses qui en
découlent.

\subsection{Résultats de la
Régression}\label{ruxe9sultats-de-la-ruxe9gression}

\begin{longtable}[]{@{}lrrrl@{}}
\caption{Tableau des résultats de la régression linéaire}\tabularnewline
\toprule\noalign{}
Coefficient & Estimate & Std\_Error & t\_value & Pr \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Coefficient & Estimate & Std\_Error & t\_value & Pr \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
(Intercept) & 13.5338116 & 21.7514794 & 0.622 & 0.534 \\
cement & 0.1104577 & 0.0069542 & 15.884 & \textless{} 2e-16 \\
blast\_furnace & 0.0840965 & 0.0084035 & 10.007 & \textless{} 2e-16 \\
fly\_ash & 0.0571293 & 0.0104619 & 5.461 & 6.05e-08 \\
water & -0.1748622 & 0.0323918 & -5.398 & 8.49e-08 \\
super\_plast & 0.3208792 & 0.0814200 & 3.941 & 8.71e-05 \\
coarse & 0.0012942 & 0.0077510 & 0.167 & 0.867 \\
fine\_aggr & -0.0005301 & 0.0088325 & -0.060 & 0.952 \\
age & 0.3112546 & 0.0093762 & 33.196 & \textless{} 2e-16 \\
\end{longtable}

\subsection{Interprétations de la
régression}\label{interpruxe9tations-de-la-ruxe9gression}

\textbf{Interprétation des p-values}

Les résultats de la régression montrent que :

\begin{itemize}
\item
  \textbf{Intercept} : La p-value est de \textbf{0.534}, ce qui est
  \textbf{supérieur à 0.05}. Nous retenons donc l'\textbf{hypothèse H0},
  selon laquelle cette valeur n'est \textbf{pas significative}.
\item
  \textbf{Les variables qui sont significatives (p \textless{} 0.05)} :
  \texttt{cement},
  \texttt{blast\_furnace},\texttt{fly\_ash},\texttt{water},
  \texttt{super\_plast} et \texttt{age}.
\end{itemize}

Nous acceptons l'\textbf{hypothèse H1}, qui indique que ces variables
ont un \textbf{effet significatif} sur la résistance du béton.

\begin{itemize}
\tightlist
\item
  \textbf{Variables non significatives au seuil de 5 \%} :
  \texttt{coarse} et \texttt{fine\_aggr}. Elles ne sont pas
  significatives, même au seuil de 10 \%, et n'ont donc \textbf{aucun
  effet statistique} sur la résistance du béton.
\end{itemize}

Ces résultats suggèrent que certaines variables ont un impact plus
marqué sur la \textbf{résistance à la compression du béton}, tandis que
d'autres jouent un rôle moins déterminant.

Au regard de ces variables significatives, nous avons constaté des
effets divers sur la variable réponse.

Pour la variable \textbf{Cement} (ciment), on remarque un effet positif
sur la variable réponse qui n'est rien d'autre que la résistance à la
compression. La valeur de cette relation est de l'ordre de
\textbf{0.110}, cela signifie que si le ciment augmente d'une unité
alors la résistance à la compression augmente de \textbf{0.110 unité}.

Ensuite, pour la variable \textbf{blast\_furnace} (laitier de haut
fourneau), la relation est positive. Cela signifie qu'une hausse de la
variable en question d'une unité entraîne une augmentation de
\textbf{0.084 unité} de la variable cible.

Puis, on s'intéresse à la variable \textbf{fly\_ash} (cendres volantes)
qui est positivement corrélée avec la variable endogène
(\textbf{0.057}). Cela pourrait être traduit comme étant une
augmentation moins proportionnelle de la résistance comparée aux cendres
volantes.

Par la suite, nous remarquons une relation négative entre la variable
\textbf{water} et la résistance à la compression. Cette relation est de
l'ordre de \textbf{-0.175}, c'est-à-dire que l'augmentation de l'eau
d'une unité entraîne une baisse de la résistance de \textbf{0.175
unité}. Cela rejoint notre conclusion de l'analyse multivariée.

Par ailleurs, la relation de notre variable cible avec la variable
\textbf{super\_plast} est de \textbf{0.321}, qui est la relation la plus
importante dans notre modèle ! Cette relation est positive, ce qui
signifie que l'\textbf{additif chimique est très important pour
augmenter la résistance de notre béton}. Cela confirme nos propos suite
à l'analyse multivariée.

Enfin, on s'aperçoit que la variable \textbf{age} est positivement
corrélée avec la variable réponse avec une valeur de \textbf{0.311}, ce
qui confirme les résultats des revues qui stipulent que la résistance
augmente avec le temps.

\subsection{Diagnostic initial du modèle sans interactions (avec toutes
les
variables)}\label{diagnostic-initial-du-moduxe8le-sans-interactions-avec-toutes-les-variables}

\textbf{Test de Durbin-Watson}

\begin{longtable}[]{@{}ll@{}}
\caption{Durbin-Watson Test Results}\tabularnewline
\toprule\noalign{}
Description & Valeur \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Description & Valeur \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
DW & 1.235 \\
p-value & \textless{} 2.2e-16 \\
Alternative hypothesis & true autocorrelation is not 0 \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  \textbf{Durbin-Watson statistic (DW)} : \textbf{1.235}\\
\item
  \textbf{p-value} : \textbf{\textless{} 2.2e-16}\\
\item
  \textbf{Hypothèse alternative} : L'autocorrélation des erreurs est
  \textbf{différente de 0}.
\end{itemize}

La p-value étant inférieure à 0.05, nous rejetons l'\textbf{hypothèse
H0} et acceptons l'\textbf{hypothèse H1},\\
ce qui signifie que \textbf{les erreurs sont fortement corrélées}.

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-38-1.pdf}

On remarque que plusieurs barres sortent de l'intervalle de confiance,
ce qui vient soutenir la conclusion\\
du test de Durbin-Watson selon laquelle les erreurs sont
\textbf{autocorrélées}.

\textbf{Test de Breusch-Pagan}

\begin{longtable}[]{@{}ll@{}}
\caption{Breusch-Pagan Test Results}\tabularnewline
\toprule\noalign{}
Description & Valeur \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Description & Valeur \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Breusch-Pagan statistic (BP) & 137.02 \\
Degrés de liberté (df) & 8 \\
p-value & \textless{} 2.2e-16 \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  \textbf{Breusch-Pagan statistic (BP)} : \textbf{137.02}\\
\item
  \textbf{Degrés de liberté (df)} : \textbf{8}\\
\item
  \textbf{p-value} : \textbf{\textless{} 2.2e-16}
\end{itemize}

D'après les résultats du \textbf{test de Breusch-Pagan}, nous acceptons
l'\textbf{hypothèse H1},\\
ce qui signifie que \textbf{l'erreur est hétéroscédastique}. Cela
indique qu'il existe une \textbf{dépendance}\\
entre la variance des erreurs et les \textbf{variables explicatives}.

\textbf{Test de Normalité de Shapiro-Wilk}

\begin{longtable}[]{@{}ll@{}}
\caption{Shapiro-Wilk Normality Test Results}\tabularnewline
\toprule\noalign{}
Description & Valeur \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Description & Valeur \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Shapiro-Wilk statistic (W) & 0.99324 \\
p-value & 0.0002368 \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  \textbf{Shapiro-Wilk statistic (W)} : \textbf{0.99324}\\
\item
  \textbf{p-value} : \textbf{0.0002368}
\end{itemize}

D'après les résultats du \textbf{test de Shapiro-Wilk}, la p-value est
\textbf{inférieure au seuil de 5 \%}.\\
Nous rejetons donc l'\textbf{hypothèse nulle (H0)} de normalité des
erreurs.\\
Par conséquent, \textbf{les erreurs ne suivent pas une distribution
normale}.

\begin{longtable}[]{@{}rrrrrr@{}}
\caption{A tibble: 6 x 6}\tabularnewline
\toprule\noalign{}
.fitted & .resid & .hat & .sigma & .cooksd & .std.resid \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
.fitted & .resid & .hat & .sigma & .cooksd & .std.resid \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
53.5 & 26.50 & 0.01370 & 10.4 & 0.010200 & 2.570 \\
53.7 & 8.14 & 0.01290 & 10.4 & 0.000902 & 0.788 \\
56.8 & -16.50 & 0.01700 & 10.4 & 0.004950 & -1.600 \\
67.7 & -26.60 & 0.02870 & 10.4 & 0.022100 & -2.600 \\
60.9 & -16.60 & 0.03060 & 10.4 & 0.009230 & -1.620 \\
26.9 & 20.20 & 0.00694 & 10.4 & 0.002940 & 1.950 \\
\end{longtable}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-42-1.pdf}

Le nuage de points montre une dispersion relativement homogène autour de
zéro, mais la courbe rouge (loess) présente une légère forme incurvée,
ce qui suggère une possible non-linéarité dans la relation entre les
variables explicatives et la variable réponse.

Il n'y a pas de motif très marqué, mais la présence de cette courbe
légèrement incurvée pourrait indiquer que certaines transformations ou
interactions pourraient améliorer le modèle.

Les observations 338, 340 et 361 présentent les résidus les plus élevés,
mais ne semblent pas influentes ou aberrantes à ce stade.

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-43-1.pdf}

Dans notre cas, la \textbf{courbe rouge n'est pas horizontale} et ne
sépare pas les points de manière homogène\\
de part et d'autre. Cela indique que \textbf{les erreurs ne sont pas
homogènes}, ce qui confirme la conclusion\\
du \textbf{test de Breusch-Pagan}.

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-44-1.pdf}

Le Q-Q plot montre que la majorité des résidus sont proches de la droite
théorique, ce qui suggère une approximation raisonnable à la normalité.
Cependant, quelques valeurs extrêmes dans la queue droite (observations
338, 340 et 361) s'en écartent légèrement.

Bien que visuellement la normalité semble globalement respectée, le test
de Shapiro-Wilk rejette l'hypothèse de normalité au seuil de 5 \%,
indiquant que les résidus ne suivent pas une loi normale.

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-45-1.pdf}

Tous les points situés \textbf{à droite de la droite verticale bleue}
sont des \textbf{points leviers extrêmes},\\
c'est-à-dire des \textbf{valeurs extrêmes des variables explicatives}.

De plus, tous les points \textbf{en dehors de l'intervalle formé par les
pointillés jaunes} sont des \textbf{outliers},\\
c'est-à-dire des \textbf{valeurs extrêmes de la variable cible}.

Dans notre cas, nous avons \textbf{deux outliers} et \textbf{plusieurs
points leviers extrêmes}.

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-46-1.pdf}

Suite à l'observation des résultats donnés par le graphique, on remarque
que \textbf{plusieurs points dépassent la ligne}\\
formée par les \textbf{pointillés rouges}, qui représente le seuil à
partir duquel un point est \textbf{considéré comme influent}.

Les \textbf{bétons 57, 225 et 611} sont les \textbf{plus influents}.

\subsection{Selection du Meilleur
modèle}\label{selection-du-meilleur-moduxe8le}

L'objectif de cette partie est de choisir le modèle de regression
linéaire qui prédise au mieux la variable que l'on veut expliquer, c'est
à dire ici la résistance à la compression du béton. On peut alors
regarder premièrement la selection du meilleur modèle en utilisant le
critère BIC

\begin{verbatim}
## Initialization...
## TASK: Exhaustive screening of candidate set.
## Fitting...
## 
## After 50 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast
## Crit= 7564.29155889758
## Mean crit= 7878.64801735781
## 
## After 100 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast
## Crit= 7564.29155889758
## Mean crit= 7850.06359357518
## 
## After 150 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+age
## Crit= 6840.15551689892
## Mean crit= 7685.32713855584
## 
## After 200 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7457.27122102457
## 
## After 250 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7278.05906840489
## Completed.
\end{verbatim}

\begin{verbatim}
## Initialization...
## TASK: Genetic algorithm in the candidate set.
## Initialization...
## Algorithm started...
## 
## After 10 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+fine_aggr+age
## Crit= 6836.89267770694
## Mean crit= 7593.44807488735
## Change in best IC: -3163.10732229306 / Change in mean IC: -2406.55192511265
## 
## After 20 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7560.13428541751
## Change in best IC: -6.7354409945392 / Change in mean IC: -33.313789469833
## 
## After 30 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7508.98029739617
## Change in best IC: 0 / Change in mean IC: -51.153988021345
## 
## After 40 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7457.63128235804
## Change in best IC: 0 / Change in mean IC: -51.3490150381267
## 
## After 50 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7403.399879041
## Change in best IC: 0 / Change in mean IC: -54.2314033170378
## 
## After 60 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7374.09830857244
## Change in best IC: 0 / Change in mean IC: -29.3015704685668
## 
## After 70 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7356.43961924158
## Change in best IC: 0 / Change in mean IC: -17.6586893308522
## 
## After 80 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7333.23261946562
## Change in best IC: 0 / Change in mean IC: -23.2069997759672
## 
## After 90 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7308.2452474095
## Change in best IC: 0 / Change in mean IC: -24.9873720561163
## 
## After 100 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7293.01133220841
## Change in best IC: 0 / Change in mean IC: -15.2339152010863
## 
## After 110 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7285.0470213154
## Change in best IC: 0 / Change in mean IC: -7.96431089301768
## 
## After 120 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7284.83523584866
## Change in best IC: 0 / Change in mean IC: -0.211785466738547
## 
## After 130 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7268.23577109265
## Change in best IC: 0 / Change in mean IC: -16.5994647560092
## 
## After 140 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7246.75270373996
## Change in best IC: 0 / Change in mean IC: -21.4830673526867
## 
## After 150 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7245.37068144482
## Change in best IC: 0 / Change in mean IC: -1.38202229514263
## 
## After 160 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7244.93377312344
## Change in best IC: 0 / Change in mean IC: -0.436908321375995
## 
## After 170 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7244.93377312344
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 180 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7244.73909764022
## Change in best IC: 0 / Change in mean IC: -0.194675483222454
## 
## After 190 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7237.96370669489
## Change in best IC: 0 / Change in mean IC: -6.77539094532858
## 
## After 200 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7237.96370669489
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 210 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7237.96370669489
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 220 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7234.91303007765
## Change in best IC: 0 / Change in mean IC: -3.05067661724661
## 
## After 230 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7234.91303007765
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 240 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7227.62393985456
## Change in best IC: 0 / Change in mean IC: -7.28909022308289
## 
## After 250 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7226.74261958458
## Change in best IC: 0 / Change in mean IC: -0.881320269985736
## 
## After 260 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7226.74261958458
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 270 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7226.74261958458
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 280 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7226.74261958458
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 290 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7220.6976170682
## Change in best IC: 0 / Change in mean IC: -6.04500251638183
## 
## After 300 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7220.6976170682
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 310 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7220.6976170682
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 320 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7220.6976170682
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 330 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7220.6976170682
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 340 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7219.26151822845
## Change in best IC: 0 / Change in mean IC: -1.43609883974204
## 
## After 350 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7219.26151822845
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 360 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7219.26151822845
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 370 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7219.26151822845
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 380 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7219.26151822845
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 390 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6830.1572367124
## Mean crit= 7219.26151822845
## Improvements in best and average IC have bebingo en below the specified goals.
## Algorithm is declared to have converged.
## Completed.
\end{verbatim}

\begin{verbatim}
## [1] "y_concrete_compresive ~ 1 + cement + blast_furnace + fly_ash + "
## [2] "    water + super_plast + age"
\end{verbatim}

\begin{verbatim}
## [1] "y_concrete_compresive ~ 1 + cement + blast_furnace + fly_ash + "
## [2] "    water + super_plast + age"
\end{verbatim}

Selon le critére aic, le premier modèle qui a été selectionné par
l'algorithme exhaustive est le suivant : y\_concrete\_compresive
\textasciitilde{} 1 + cement + blast\_furnace + fly\_ash + water +
super\_plast + age.

selon la deuxième méthode qui est l'algorithme génétique, on a :
y\_concrete\_compresive \textasciitilde{} y\_concrete\_compresive
\textasciitilde{} 1 + cement + blast\_furnace + fly\_ash + water +
super\_plast + age'' les deux methodes nous donnent le meme modèle.

On peut alors voir que les variables \texttt{coarse} et
\texttt{fine\_aggr} on étées retirées du modèle par manque de
significativité et impact sur la valeur de l'erreur empirique. On peut
se demander si l'utilisation d'un autre critère pour selectioner le
meilleur modèle peut changer le modèle optimal obtenue précédemment.
Essayons le critère AIC.

\begin{verbatim}
## Initialization...
## TASK: Exhaustive screening of candidate set.
## Fitting...
## 
## After 50 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast
## Crit= 7530.21573803479
## Mean crit= 7855.99703439362
## 
## After 100 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast
## Crit= 7530.21573803479
## Mean crit= 7824.97094198255
## 
## After 150 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+age
## Crit= 6806.07969603613
## Mean crit= 7656.58448012012
## 
## After 200 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7426.01574811718
## 
## After 250 models:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7245.05420191207
## Completed.
\end{verbatim}

\begin{verbatim}
## Initialization...
## TASK: Genetic algorithm in the candidate set.
## Initialization...
## Algorithm started...
## 
## After 10 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7540.81737870367
## Change in best IC: -3208.78655855936 / Change in mean IC: -2459.18262129633
## 
## After 20 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7484.96425295491
## Change in best IC: 0 / Change in mean IC: -55.8531257487666
## 
## After 30 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7409.68708199348
## Change in best IC: 0 / Change in mean IC: -75.2771709614244
## 
## After 40 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7361.89874914248
## Change in best IC: 0 / Change in mean IC: -47.7883328509997
## 
## After 50 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7330.94398206818
## Change in best IC: 0 / Change in mean IC: -30.9547670743004
## 
## After 60 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7294.31041097024
## Change in best IC: 0 / Change in mean IC: -36.6335710979456
## 
## After 70 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7271.31218947834
## Change in best IC: 0 / Change in mean IC: -22.9982214918937
## 
## After 80 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7261.49982706729
## Change in best IC: 0 / Change in mean IC: -9.81236241104853
## 
## After 90 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7247.32410564259
## Change in best IC: 0 / Change in mean IC: -14.1757214247064
## 
## After 100 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7230.56528117628
## Change in best IC: 0 / Change in mean IC: -16.7588244663057
## 
## After 110 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7229.21851807587
## Change in best IC: 0 / Change in mean IC: -1.34676310041232
## 
## After 120 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7217.20462885096
## Change in best IC: 0 / Change in mean IC: -12.0138892249142
## 
## After 130 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7203.17842579272
## Change in best IC: 0 / Change in mean IC: -14.0262030582371
## 
## After 140 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7203.17842579272
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 150 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7203.16307540418
## Change in best IC: 0 / Change in mean IC: -0.0153503885430837
## 
## After 160 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7202.09925910297
## Change in best IC: 0 / Change in mean IC: -1.06381630120541
## 
## After 170 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7198.16560588505
## Change in best IC: 0 / Change in mean IC: -3.93365321792317
## 
## After 180 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7198.16560588505
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 190 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7198.16560588505
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 200 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7192.05614403497
## Change in best IC: 0 / Change in mean IC: -6.10946185007288
## 
## After 210 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7192.05614403497
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 220 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7192.05614403497
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 230 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7192.05614403497
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 240 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7192.05614403497
## Change in best IC: 0 / Change in mean IC: 0
## 
## After 250 generations:
## Best model: y_concrete_compresive~1+cement+blast_furnace+fly_ash+water+super_plast+age
## Crit= 6791.21344144064
## Mean crit= 7192.05614403497
## Improvements in best and average IC have bebingo en below the specified goals.
## Algorithm is declared to have converged.
## Completed.
\end{verbatim}

\begin{verbatim}
## [1] "y_concrete_compresive ~ 1 + cement + blast_furnace + fly_ash + "
## [2] "    water + super_plast + age"
\end{verbatim}

\begin{verbatim}
## [1] "y_concrete_compresive ~ 1 + cement + blast_furnace + fly_ash + "
## [2] "    water + super_plast + age"
\end{verbatim}

La encore, le même modèle \texttt{cement\ +\ blast\_furnace\ +}
\texttt{fly\_ash\ +\ water\ +\ super\_plast\ +\ age} ressort, ce qui
était assez prévisible car ces deux critères sont très similaires.

Selon le critére aic, le premier modèle qui a été selectionné par
l'algorithme exhaustive est le suivant :
y\_concrete\_compresive\textasciitilde1+cement+blast\_furnace+fly\_ash+water+super\_plast+age.

selon la deuxième méthode qui est l'algorithme génétique, on a :
y\_concrete\_compresive \textasciitilde{} 1 + cement + blast\_furnace +
fly\_ash + water + super\_plast + age'' les deux methodes nous donnent
le meme modèle.

\begin{verbatim}
## Start:  AIC=4065.85
## y_concrete_compresive ~ cement + blast_furnace + fly_ash + water + 
##     super_plast + coarse + fine_aggr + age
## 
##                 Df Sum of Sq    RSS    AIC   F value    Pr(>F)    
## - fine_aggr      1         0  64868 4063.9    0.0036    0.9522    
## - coarse         1         2  64869 4063.9    0.0279    0.8674    
## <none>                        64867 4065.9                        
## - super_plast    1      1058  65926 4079.4   15.5318 8.706e-05 ***
## - water          1      1986  66853 4092.8   29.1421 8.494e-08 ***
## - fly_ash        1      2032  66899 4093.5   29.8192 6.053e-08 ***
## - blast_furnace  1      6824  71691 4160.0  100.1476 < 2.2e-16 ***
## - cement         1     17190  82058 4289.8  252.2890 < 2.2e-16 ***
## - age            1     75088 139955 4802.8 1101.9937 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Step:  AIC=4063.86
## y_concrete_compresive ~ cement + blast_furnace + fly_ash + water + 
##     super_plast + coarse + age
## 
##                 Df Sum of Sq    RSS    AIC   F value    Pr(>F)    
## - coarse         1        11  64878 4062.0    0.1557    0.6932    
## <none>                        64868 4063.9                        
## + fine_aggr      1         0  64867 4065.9    0.0036    0.9522    
## - super_plast    1      1082  65949 4077.8   15.8930 7.215e-05 ***
## - water          1      5245  70112 4136.6   77.0511 < 2.2e-16 ***
## - fly_ash        1      5304  70172 4137.4   77.9273 < 2.2e-16 ***
## - blast_furnace  1     26163  91030 4387.5  384.3664 < 2.2e-16 ***
## - cement         1     63929 128797 4721.0  939.2137 < 2.2e-16 ***
## - age            1     75321 140188 4802.4 1106.5715 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Step:  AIC=4062.01
## y_concrete_compresive ~ cement + blast_furnace + fly_ash + water + 
##     super_plast + age
## 
##                 Df Sum of Sq    RSS    AIC   F value    Pr(>F)    
## <none>                        64878 4062.0                        
## + coarse         1        11  64868 4063.9    0.1557    0.6932    
## + fine_aggr      1         9  64869 4063.9    0.1314    0.7170    
## - super_plast    1      1149  66027 4076.9   16.8912 4.299e-05 ***
## - fly_ash        1      5359  70237 4136.3   78.8040 < 2.2e-16 ***
## - water          1      6844  71722 4156.4  100.6397 < 2.2e-16 ***
## - blast_furnace  1     28681  93559 4411.8  421.7378 < 2.2e-16 ***
## - cement         1     68363 133241 4751.6 1005.2373 < 2.2e-16 ***
## - age            1     75394 140272 4801.0 1108.6315 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{verbatim}
## Start:  AIC=5422.78
## y_concrete_compresive ~ 1
## 
##                 Df Sum of Sq    RSS    AIC  F value    Pr(>F)    
## + age            1     72105 198590 5127.1 348.1968 < 2.2e-16 ***
## + cement         1     62942 207754 5170.5 290.5420 < 2.2e-16 ***
## + super_plast    1     44529 226166 5252.1 188.8142 < 2.2e-16 ***
## + water          1     34144 236551 5295.2 138.4248 < 2.2e-16 ***
## + coarse         1      7440 263256 5398.0  27.1011 2.362e-07 ***
## + blast_furnace  1      5874 264821 5403.7  21.2710 4.527e-06 ***
## + fine_aggr      1      5602 265093 5404.7  20.2670 7.563e-06 ***
## + fly_ash        1      1436 269259 5419.7   5.1145   0.02395 *  
## <none>                       270695 5422.8                       
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Step:  AIC=5127.12
## y_concrete_compresive ~ age
## 
##                 Df Sum of Sq    RSS    AIC F value    Pr(>F)    
## + cement         1     67528 131063 4729.8 493.593 < 2.2e-16 ***
## + super_plast    1     38724 159867 4920.7 232.050 < 2.2e-16 ***
## + water          1     31044 167547 4965.8 177.502 < 2.2e-16 ***
## + coarse         1      8459 190132 5087.3  42.620 1.077e-10 ***
## + fine_aggr      1      7676 190914 5091.2  38.518 8.066e-10 ***
## + blast_furnace  1      7419 191171 5092.5  37.180 1.560e-09 ***
## + fly_ash        1      2732 195859 5115.8  13.363 0.0002706 ***
## <none>                       198590 5127.1                      
## - age            1     72105 270695 5422.8 348.197 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Step:  AIC=4729.75
## y_concrete_compresive ~ age + cement
## 
##                 Df Sum of Sq    RSS    AIC  F value    Pr(>F)    
## + super_plast    1     33652  97410 4446.6 330.6147 < 2.2e-16 ***
## + blast_furnace  1     25164 105898 4526.9 227.4110 < 2.2e-16 ***
## + water          1     23078 107985 4545.6 204.5271 < 2.2e-16 ***
## + coarse         1      4325 126738 4699.5  32.6565 1.468e-08 ***
## + fly_ash        1      2651 128412 4712.1  19.7565 9.825e-06 ***
## + fine_aggr      1      1090 129973 4723.7   8.0269  0.004706 ** 
## <none>                       131063 4729.8                       
## - cement         1     67528 198590 5127.1 493.5929 < 2.2e-16 ***
## - age            1     76691 207754 5170.5 560.5706 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Step:  AIC=4446.58
## y_concrete_compresive ~ age + cement + super_plast
## 
##                 Df Sum of Sq    RSS    AIC  F value    Pr(>F)    
## + blast_furnace  1     21785  75625 4205.3 275.3942 < 2.2e-16 ***
## + fine_aggr      1      4221  93190 4406.0  43.2971 7.737e-11 ***
## + water          1      2283  95127 4425.8  22.9430 1.933e-06 ***
## + fly_ash        1      1592  95819 4432.8  15.8797 7.263e-05 ***
## + coarse         1       511  96899 4443.5   5.0409   0.02498 *  
## <none>                        97410 4446.6                       
## - super_plast    1     33652 131063 4729.8 330.6147 < 2.2e-16 ***
## - cement         1     62457 159867 4920.7 613.5993 < 2.2e-16 ***
## - age            1     70891 168301 4970.1 696.4630 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Step:  AIC=4205.31
## y_concrete_compresive ~ age + cement + super_plast + blast_furnace
## 
##                 Df Sum of Sq    RSS    AIC  F value    Pr(>F)    
## + water          1      5388  70237 4136.3  73.2545 < 2.2e-16 ***
## + fly_ash        1      3903  71722 4156.4  51.9651 1.147e-12 ***
## + coarse         1       723  74902 4198.1   9.2160  0.002464 ** 
## <none>                        75625 4205.3                       
## + fine_aggr      1        73  75552 4206.4   0.9179  0.338282    
## - blast_furnace  1     21785  97410 4446.6 275.3942 < 2.2e-16 ***
## - super_plast    1     30273 105898 4526.9 382.6917 < 2.2e-16 ***
## - age            1     74591 150216 4862.8 942.9251 < 2.2e-16 ***
## - cement         1     78288 153913 4886.2 989.6569 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Step:  AIC=4136.29
## y_concrete_compresive ~ age + cement + super_plast + blast_furnace + 
##     water
## 
##                 Df Sum of Sq    RSS    AIC   F value    Pr(>F)    
## + fly_ash        1      5359  64878 4062.0   78.8040 < 2.2e-16 ***
## + fine_aggr      1      1497  68741 4117.6   20.7740 5.839e-06 ***
## <none>                        70237 4136.3                        
## + coarse         1        66  70172 4137.4    0.8909    0.3455    
## - water          1      5388  75625 4205.3   73.2545 < 2.2e-16 ***
## - super_plast    1      7738  77976 4234.7  105.2161 < 2.2e-16 ***
## - blast_furnace  1     24890  95127 4425.8  338.4222 < 2.2e-16 ***
## - age            1     74879 145117 4831.6 1018.1138 < 2.2e-16 ***
## - cement         1     76726 146963 4843.8 1043.2183 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Step:  AIC=4062.01
## y_concrete_compresive ~ age + cement + super_plast + blast_furnace + 
##     water + fly_ash
## 
##                 Df Sum of Sq    RSS    AIC   F value    Pr(>F)    
## <none>                        64878 4062.0                        
## + coarse         1        11  64868 4063.9    0.1557    0.6932    
## + fine_aggr      1         9  64869 4063.9    0.1314    0.7170    
## - super_plast    1      1149  66027 4076.9   16.8912 4.299e-05 ***
## - fly_ash        1      5359  70237 4136.3   78.8040 < 2.2e-16 ***
## - water          1      6844  71722 4156.4  100.6397 < 2.2e-16 ***
## - blast_furnace  1     28681  93559 4411.8  421.7378 < 2.2e-16 ***
## - cement         1     68363 133241 4751.6 1005.2373 < 2.2e-16 ***
## - age            1     75394 140272 4801.0 1108.6315 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

A ce niveau, nous avons utilisé le critère Fisher. nous avons utilisé
deux methodes à savoir l'algorithme bidirectionnel descendante puis
l'algorithme bidirectionnel ascendante. avec la première méthode, on a :
y\_concrete\_compresive \textasciitilde{} cement + blast\_furnace +
fly\_ash + water + super\_plast + age. La deuxième méthode quant à elle
nous donne le modèle suivant : y\_concrete\_compresive \textasciitilde{}
age + cement + super\_plast + blast\_furnace + water + fly\_ash. Avec
les deux méthodes, nous avons pratiquement les memes résultats. De plus,
les deux autres critères à savoir bic et aic ont donné les memes
résulats avec les deux algoritmes à savoir : l'exhaustif et génétique.

\textbf{Erreur théorique}

On va appliquer ici les méthode pour estimer l'erreur théorique d'un
modèle : on compare les modèles générés par le critére bic, aic et
Fisher.

\paragraph{Méthode 1 : estimation de l'erreur par la méthode
apprentissage/validation}\label{muxe9thode-1-estimation-de-lerreur-par-la-muxe9thode-apprentissagevalidation}

\begin{verbatim}
## Warning: package 'ISLR' was built under R version 4.4.2
\end{verbatim}

\begin{verbatim}
## [1] 71.627
\end{verbatim}

\begin{verbatim}
## [1] 71.28255
\end{verbatim}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-50-1.pdf}

\begin{verbatim}
## [1] "Erreur de prévision finale: 69.0386"
\end{verbatim}

On voit ici que pour la méthode d'apprentissage validation, le modèle
retenu avec les AIC/BIC/Fisher a une erreur théorique qui est inferieure
à celle du modèle complet c'est-à-dire que ce modèle est plus performant
que le modèle complet. modèle retunu avec les critères AIC/BIC/Fisher :
``y\_concrete\_compresive \textasciitilde{} age + cement + super\_plast
+ blast\_furnace + water + fly\_ash''. En répétant la méthode plusieurs
fois (dans ce cas 500 fois), on a eu une erreur théorique inferieure à
celui des deux méthodes. Malgrè les inconvenients de cette méthode, en
répetant la méthode plusieurs fois (la loi de grands nombres), l'erreur
théorique tend vers l'erreur théorique optimale. On regarde à présent la
méthode de validation croisée K-fold.

\paragraph{Méthode 2 : estimation de l'erreur par la K-fold
CV}\label{muxe9thode-2-estimation-de-lerreur-par-la-k-fold-cv}

\begin{verbatim}
## Erreur estimée par validation croisée ( 10 -fold) : 109.4825
\end{verbatim}

On trouve une erreur plus importante que celle de la méthode précédente.
L'erreur théorique de cette méthode est de 109.43 contre 69.24 pour la
méthode apprentissage/validation. L'estimation de l'erreur théorique de
prévision pour la méthode apprentissage/validation dépend de la
partition aléatoire, c'est moins précis car on n'utilise qu'une partie
des données pour entrainer le modèle.

\paragraph{Sélection du meilleur
modèle}\label{suxe9lection-du-meilleur-moduxe8le}

Pour la sélection du modèle, on s'est appuyée sur trois approches
complémentaires :\\
1. les critères statistiques (AIC/BIC/Fisher),\\
2. l'analyse descriptive (notamment l'ACP),\\
3. la littérature sur les propriétés du béton.

\textbf{1. Sélection par AIC/BIC/Fisher}\\
Parmi les huit variables initiales, six ont été retenues : \emph{age},
\emph{cement}, \emph{fly\_ash}, \emph{water}, \emph{super\_plast} et
\emph{blast\_furnace}.\\
Les variables \emph{fine\_aggr} et \emph{coarse} ont été écartées selon
les critères AIC/BIC.

\textbf{2. Apport de l'ACP}\\
L'ACP a permis d'identifier des interactions pertinentes qu'on a testé
:\\
- Opposition \emph{water} / \emph{super\_plast} (Dim 1) → test de
l'interaction \emph{water * super\_plast}.\\
- Projection de \emph{fly\_ash} et \emph{fine\_aggr} sur Dim 2 → test de
\emph{cement * fine\_aggr} pour explorer leur effet combiné sur la
compacité et la résistance (non retenue). - Bonne projection de
\emph{age} (Dim 4) → ajout de l'interaction \emph{age * cement}.\\
- Opposition entre \emph{coarse} et \emph{super\_plast} sur Dim 2 →
interaction testée malgré l'exclusion initiale de \emph{coarse} avec
AIC, mais non retenue car non significative et perturbant l'ajustement
du modèle.

\textbf{3. Apport de la littérature}\\
Des interactions basées sur la littérature ont été intégrées :\\
- \emph{age * blast\_furnace} : le laitier améliore la résistance
surtout après plusieurs jours.\\
- \emph{age * fly\_ash} : les cendres volantes renforcent le béton avec
le temps.\\
- \emph{water²} : effet non linéaire du rapport eau/ciment.

\textbf{Modèle final retenu}\\
Variables principales : \emph{age}, \emph{cement},
\emph{blast\_furnace}, \emph{fly\_ash}, \emph{water} (centrée pour
réduire la colinéarité avec \emph{water²}), \emph{super\_plast}\\
Interactions retenues :\\
- \emph{age * cement}\\
- \emph{age * blast\_furnace}\\
- \emph{age * fly\_ash}\\
- \emph{water\_c * super\_plast}\\
- \emph{water\_c²}

Les résultats ci-dessous correspondent au modèle final ajusté, incluant
les interactions retenues à partir de l'ACP, de la littérature et des
critères AIC/BIC.

\begin{verbatim}
## 
## Call:
## glm(formula = y_concrete_compresive ~ age * cement + water_c + 
##     water_c2 + super_plast * water_c + blast_furnace + fly_ash + 
##     age * blast_furnace + age * fly_ash, data = bdd_final)
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(>|t|)    
## (Intercept)         -9.3399340  1.8114560  -5.156 3.07e-07 ***
## age                  0.0928123  0.0443613   2.092 0.036687 *  
## cement               0.0968491  0.0047159  20.537  < 2e-16 ***
## water_c             -0.2952547  0.0274903 -10.740  < 2e-16 ***
## water_c2             0.0016766  0.0005175   3.240 0.001239 ** 
## super_plast          0.4431133  0.0778203   5.694 1.65e-08 ***
## blast_furnace        0.0543417  0.0055726   9.752  < 2e-16 ***
## fly_ash              0.0144983  0.0089183   1.626 0.104351    
## age:cement           0.0004085  0.0001145   3.569 0.000377 ***
## water_c:super_plast  0.0179500  0.0031173   5.758 1.15e-08 ***
## age:blast_furnace    0.0008896  0.0001324   6.720 3.13e-11 ***
## age:fly_ash          0.0009277  0.0001949   4.760 2.23e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for gaussian family taken to be 62.92863)
## 
##     Null deviance: 270695  on 960  degrees of freedom
## Residual deviance:  59719  on 949  degrees of freedom
## AIC: 6721.6
## 
## Number of Fisher Scoring iterations: 2
\end{verbatim}

\paragraph{Comparaison des performances par validation croisée
(10-fold)}\label{comparaison-des-performances-par-validation-croisuxe9e-10-fold}

\begin{verbatim}
## Erreur estimée par validation croisée (10-fold) - modèle final : 64.5623
\end{verbatim}

Le modèle initial (basé uniquement sur les critères AIC/BIC) présente
une erreur moyenne de 109.48.\\
Le modèle final, construit en combinant les critères AIC/BIC, les
résultats de l'ACP et les apports de la littérature, a une erreur de
64.56.

\paragraph{R2 ajusté}\label{r2-ajustuxe9}

\begin{verbatim}
## R² ajusté du modèle : 0.7768
\end{verbatim}

Le R² ajusté du modèle final est de 0.7768, ce qui signifie que le
modèle explique environ 78 \% de la variabilité observée dans la
résistance à la compression.

\subsection{Diagnostic du modèle final
retenu}\label{diagnostic-du-moduxe8le-final-retenu}

\subsubsection{Test de Durbin-Watson}\label{test-de-durbin-watson}

\begin{verbatim}
## 
##  Durbin-Watson test
## 
## data:  modele_complet
## DW = 1.2214, p-value < 2.2e-16
## alternative hypothesis: true autocorrelation is greater than 0
\end{verbatim}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-57-1.pdf} Le
statistique de Durbin-Watson est égal à 1.22, avec une p-value très
petite (\textless{} 2.2e-16). Cela signifie que les erreurs du modèle
sont autocorrélées.

\subsubsection{Test de Breusch-Pagan}\label{test-de-breusch-pagan}

\begin{verbatim}
## 
##  studentized Breusch-Pagan test
## 
## data:  modele_complet
## BP = 150.28, df = 11, p-value < 2.2e-16
\end{verbatim}

Le test de Breusch-Pagan donne une statistique de 150.28 avec 11 degrés
de liberté, et une p-value inférieure à 2.2e-16. Cela signifie que les
erreurs du modèle ne sont pas homogènes : il y a hétéroscédasticité.

\subsubsection{Test de normalité de
Shapiro-Wilk}\label{test-de-normalituxe9-de-shapiro-wilk}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(modele_complet)
## W = 0.99088, p-value = 1.14e-05
\end{verbatim}

Le test de Shapiro-Wilk donne une statistique de W = 0.99088 avec une
p-value = 1.14e-05. Cette p-value étant inférieure à 0.05, on rejette
l'hypothèse de normalité des résidus.

\subsubsection{Graphique : Résidus vs Valeurs
ajustées}\label{graphique-ruxe9sidus-vs-valeurs-ajustuxe9es}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-60-1.pdf} Le
nuage de points est globalement centré autour de zéro, mais la courbe
rouge montre une légère courbure. Cela suggère que la relation n'est pas
parfaitement linéaire, malgré l'ajout d'interactions et de
transformations.

\subsubsection{Graphique : Q-Q plot}\label{graphique-q-q-plot}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-61-1.pdf}
Les observations 338, 340 et 185 s'écartent de la droite dans la partie
haute, ce qui montre quelques résidus extrêmes. Cela rejoint le résultat
du test de Shapiro-Wilk, qui avait déjà indiqué que les résidus ne sont
pas normaux.

\section{Statistique en Grande
dimension}\label{statistique-en-grande-dimension}

\subsection{methode ridge}\label{methode-ridge}

cette methode nous permet de contraindre les coefficients de telle sorte
à avoir un équilibre juste entre le biais et la variance.

\begin{verbatim}
## Loading required package: Matrix
\end{verbatim}

\begin{verbatim}
## Loaded glmnet 4.1-8
\end{verbatim}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-62-1.pdf}

\begin{verbatim}
## Warning: Option grouped=FALSE enforced in cv.glmnet, since < 3 observations per
## fold
\end{verbatim}

\begin{verbatim}
## [1] "Meilleur lambda: 0.8662047727533"
\end{verbatim}

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-62-2.pdf}

\begin{verbatim}
## [1] "Erreur MSE minimale: 69.9738363782654"
\end{verbatim}

\begin{verbatim}
## [1] "Coefficients optimaux:"
\end{verbatim}

\begin{verbatim}
## 7 x 1 sparse Matrix of class "dgCMatrix"
##                        s1
## (Intercept)   17.14454013
## cement         0.09734465
## blast_furnace  0.07021218
## fly_ash        0.03744530
## water         -0.15953543
## super_plast    0.45084306
## age            0.29440887
\end{verbatim}

On remarque que l'erreur théorique est de 69.97 avec le meilleur lambda
qui est de 0.86 .

\subsection{methode lasso}\label{methode-lasso}

cette deuxième nous permet de selectionner les variables à inserer dans
le modèle tout en contraignant egalement les coefficients de telle sorte
qu'il aii équilibre parfait entre biais et variance.

\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-63-1.pdf}
\includegraphics{rmd_final_files/figure-latex/unnamed-chunk-63-2.pdf}

\begin{verbatim}
## Lambda optimal: 0.04731451
\end{verbatim}

\begin{verbatim}
## 9 x 1 sparse Matrix of class "dgCMatrix"
##                         s1
## (Intercept)   17.752885121
## cement         0.107597256
## blast_furnace  0.080643114
## fly_ash        0.052423318
## water         -0.176721943
## super_plast    0.336140535
## coarse         .          
## fine_aggr     -0.002259712
## age            0.309551398
\end{verbatim}

\begin{verbatim}
## 
## Variables sélectionnées par Lasso:
\end{verbatim}

\begin{verbatim}
## [1] "cement"        "blast_furnace" "fly_ash"       "water"        
## [5] "super_plast"   "fine_aggr"     "age"
\end{verbatim}

\begin{verbatim}
## 
## Erreur MSE minimale: 68.88931
\end{verbatim}

Pour la méthode de lasso qui est une méthode de selection de variable,
on remarque à la difference des autres methodes et critéres de
selection, elle ajoute fine\_aggr. le modèle donne par cette méthode est
la suivante : ``y\_concrete\_compresive'' = cement'' +
``blast\_furnace'' + ``fly\_ash'' + ``water'' + ``super\_plast'' +
``fine\_aggr'' + ``age''. Son erreur théorique (68.88) est inferieure à
celle de la méthode ridge(69.97) avec un lambda inferieur à celui de
méthode ridge.

\end{document}
